// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArQS6U1uVk_2IE6TRae56WdwBVAOyvXFw',
    appId: '1:310026055100:web:2ef000df276b89b557cfb9',
    messagingSenderId: '310026055100',
    projectId: 'project-ritsbook-test',
    authDomain: 'project-ritsbook-test.firebaseapp.com',
    storageBucket: 'project-ritsbook-test.appspot.com',
    measurementId: 'G-8D2WWF3GE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTMEYe8cDFFV71B1IFEunoEp6FHpkEHIY',
    appId: '1:310026055100:android:b2e1a05e989ee27657cfb9',
    messagingSenderId: '310026055100',
    projectId: 'project-ritsbook-test',
    storageBucket: 'project-ritsbook-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4EM3ZbVop9B6MkEdcf0U90dn0i7D41Xg',
    appId: '1:310026055100:ios:37df615d7b19798d57cfb9',
    messagingSenderId: '310026055100',
    projectId: 'project-ritsbook-test',
    storageBucket: 'project-ritsbook-test.appspot.com',
    iosClientId: '310026055100-3331pma8fhs8reqhk9292phj9eto5uhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectritsbookNative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4EM3ZbVop9B6MkEdcf0U90dn0i7D41Xg',
    appId: '1:310026055100:ios:37df615d7b19798d57cfb9',
    messagingSenderId: '310026055100',
    projectId: 'project-ritsbook-test',
    storageBucket: 'project-ritsbook-test.appspot.com',
    iosClientId: '310026055100-3331pma8fhs8reqhk9292phj9eto5uhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectritsbookNative',
  );
}
